### ISSUE TITLE
Examples using additional modules in separate files do not work on mybinder

### ISSUE THREAD

**Issue by mstimberg** [brian-team/brian2-binder#3]
Examples like [this one](http://brian2.readthedocs.io/en/stable/examples/frompapers.Brette_2012.Fig1.html) do not currently work on mybinder because they expect to import a module from a file in their current directory. Given that this module (e.g. [params.py](http://brian2.readthedocs.io/en/stable/examples/frompapers.Brette_2012.params.html) ) has been translated to an `.ipynb` file as well, it cannot be imported. 

I guess the easiest fix would be to add a special comment like `# NO_NOTEBOOK` to the top of such files and copy them over verbatim as `.py` files?

**Comment by thesamovar** [comment]
We could modify the way the binder script works so that it copies all files across as well as converting into ipynb?

**Comment by mstimberg** [comment]
Good point, that sounds like a better solution given that we don't have to change the example files. I initially had in mind to also remove the "Launch on binder" button on files like `params.py` in the Brian documentation, but this is just a tiny detail and probably not worth adding a cryptic comment to the files.
